name: Python Lint with Black

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
          - "3.6"
          - "3.5"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

    - name: List changed files
      id: changed-files
      run: |
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        echo "Changed files:"
        echo $CHANGED_FILES
        echo "files=${CHANGED_FILES}" >> "$GITHUB_OUTPUTS"

    - name: Install black
      run: pipx install black

    - name: Lint with Black
      run: black --check ${{ steps.changed-files.outputs.files }}